version: "3.1"

volumes:
  mariadb-pm-glpi-data:
  processmaker-glpi-backup:
  glpi-files:
  glpi-config:

services:
   mariadb:
     image: mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: GLPI-PM-DBPassw0rd
     networks:
      - glpi-pm-net
     volumes:
      - mariadb-pm-glpi-data:/var/lib/mysql:Z

   processmaker:
     depends_on:
      - mariadb
     image: wolvverine/processmaker_server_glpi
     ports:
      - "9080:9080"
     restart: always
     environment:
       PM_HOST_FULL_NAME: pmhost.domain.com
     networks:
      - glpi-pm-net
     volumes:
      - processmaker-glpi-backup:/opt/processmaker-server/Backup:Z

   glpi:
     depends_on:
     - mariadb
     image: wolvverine/docker-glpi
     ports:
      - "80:80"
     restart: always
     environment:
       PHPFPM_PM_MAX_CHILDREN: 20
       PHPFPM_PM_PROCESS_IDLE_TIMEOUT: 60s
       GLPI_CHMOD_PATHS_FILES: "yes"
       GLPI_REMOVE_INSTALLER: "no"
       GLPI_ENABLE_CRONJOB: "yes"
       TZ: "Europe/Warsaw"
       GLPI_INSTALL_PLUGINS: "\
            fusioninventory|https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi9.5%2B3.0/fusioninventory-9.5+3.0.tar.bz2,\
            processmaker|https://github.com/tomolimo/processmaker/releases/download/4.0.11/processmaker-4.0.11.zip,\
            "
     networks:
      - glpi-pm-net
     volumes:
      - glpi-files:/var/www/files:Z
      - glpi-config:/var/www/config:Z

networks:
  glpi-pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
